version: 1.0.{build}
build:
  verbosity: minimal
after_build:
  - ps : >-
       $file = (Get-ChildItem -Path "./" -Filter "DependencyAnalyzer.ps1" -Recurse -ErrorAction SilentlyContinue -Force | Select-Object -First 1);
       if($file){
          & $file.Fullname;
       }
artifacts:
    - path: .\WebApiThrottle\report.json
      name: ReportWebApiThrottleProject
    - path: .\WebApiThrottle.Demo\report.json
      name: ReportWebApiThrottleDemoProject
    - path: .\WebApiThrottleSelfHostOwinDemo\report.json
      name: ReportWebApiThrottleSelfHostOwinDemoProject  