version: 1.0.{build}
build:
  verbosity: minimal
after_build:
  - ps : |
       (Get-ChildItem -Path "./" -Filter "DependencyAnalyzer.exe" -Recurse -ErrorAction SilentlyContinue -Force | % {& $_.FullName})