version: 1.0.{build}
build:
  verbosity: minimal
after_build:
  - ps : |
       powershell Get-ChildItem -Filter DependencyAnalyzer.exe -Recurse -ErrorAction SilentlyContinue -Force | % {& $_.FullName}
	   
artifacts:
  - path: DependencyAnalyzer.exe