version: 1.0.{build}
build:
  verbosity: normal
after_build:
  powershell Get-ChildItem -Path ".\bin" -Filter DotnetDependencyAnalyzer.exe -Recurse -ErrorAction SilentlyContinue -Force | ForEach-Object{% {& $_.FullName}}